Fix email role enum issue (#12039)
pypi/warehouse pull request #12231
Opened 2022-09-17 23:00 UTC by sterbo

- Fix bug where email generated after changing user role shows enum
- Fix similar issue with Team Project Role email

2022-09-18 21:51 UTC, miketheman requested changes
Looks correct to me! There's a couple other cases that don't appear to be handled, unless they are?
https://github.com/pypi/warehouse/blob/debf2b7db71b36a884c005d92e8dc200ed222d24/warehouse/manage/views.py#L4330-L4345

2022-09-19 11:43 UTC, miketheman commented
You’re right! I missed the variable set above this section 

    role.role_name = form.role_name.data
    
That’s what we get for reusing common names in the same module. 😬

2022-09-19 11:44 UTC, miketheman approved these changes

2022-09-19 17:39 UTC, ewdurbin approved these changes

2022-09-19 17:45 UTC, merged