bow wow
pypi/warehouse pull request #13900
Opened 2023-06-09 00:56 UTC by ewdurbin

2023-06-09 01:12 UTC, dstufft commented on warehouse/forklift/legacy.py
> +    if request.registry.settings.get("warehouse.release_files_table") is not None:
Already improving the code base

2023-06-23 14:31 UTC, di requested changes
I'm in favor, speed seems to be about the same, if not a little faster.

If we merge this, this PR should also remove `flake8` from our dependencies and the `flake8` section from `setup.cfg`.

2023-06-23 15:16 UTC, di approved these changes

2024-07-23 07:21 UTC, firefly9966 approved these changes

2024-08-23 16:01 UTC, closed without merging