Documentation on how to implement a new service
pypi/warehouse pull request #16595
Opened 2024-08-29 15:11 UTC by DarkaMaul

Following the last outage due to #16302, I wrote some documentation on how a new service should be added within `warehouse`.

This may be useful for the next new developers (or serve as a review baseline). 

/cc @woodruffw @facutuesca

2024-08-29 18:29 UTC, woodruffw commented on docs/dev/development/patterns.rst
> +   - Write a ``Test<ServiceName>`` class and implement ``test_interface_matches`` function (the exact name is irrelevant) to verify that the service implementation matches the interface definition us
I think this parenthetical is implied by the context:

```suggestion
   - Write a ``Test<ServiceName>`` class and implement ``test_interface_matches`` function to verify that the service implementation matches the interface definition using the ``verifyClass`` function from zope.
```

Maybe it'd be good to link to a source example of this, though?

2024-08-29 21:50 UTC, di approved these changes
LGTM aside from outstanding comments

2024-08-29 21:50 UTC, di commented on docs/dev/development/patterns.rst
> +     which backend to use.
Probably should be something like "if there are multiple variations of the same service" or something like that.

2024-09-06 14:13 UTC, miketheman requested changes
Nice work, had some notes inline.

2024-09-06 14:13 UTC, miketheman commented on docs/dev/development/patterns.rst
> +   Warehouse uses zope_ to define interfaces. The interfaces are usually declared in a file named
nitpick: the package is specifically `zope.interface` vs zope, the framework.

2024-09-06 14:13 UTC, miketheman commented on docs/dev/development/patterns.rst
> +   This implementation contains the core logic of the service features.
suggestion: services MAY add further methods specific to the service that are not required on all implementations of the interface.

2024-09-06 14:13 UTC, miketheman commented on docs/dev/development/patterns.rst
> +`pyramid-service`_. After being registered, services are accessible using the ``find_service`` method of the
nit: the project is named `pyramid-services` (plural)

2024-09-06 14:13 UTC, miketheman commented on docs/dev/development/patterns.rst
> +To use a service, query it using ``request.find_services`` with the service interface. This
```suggestion
To use a service, query it using ``request.find_service()`` with the service interface. This
```

2024-09-06 14:13 UTC, miketheman commented on docs/dev/development/patterns.rst
> +   metrics = request.find_service(IMetricsService, context=None)
thought: `context=` is not always required/used, nor is `name=` - would it be better to show an example without `context=None`, or have examples for using named service implementations?

2024-09-18 19:03 UTC, miketheman approved these changes

2024-09-18 19:13 UTC, merged