Don't install deploy dependencies for tests
pypi/warehouse pull request #17232
Opened 2024-12-05 16:55 UTC by DarkaMaul

I believe `ddtrace` and `gunicorn` are not required when running tests.

Importing `ddtrace` is somewhat costly (tests in a container with warehouse test dependencies installed):

-  Without ddtrace
```
> time pytest --help
real	0m2.521s
user	0m2.217s
sys	0m0.255s
```

- With ddtrace
```
> time pytest --help
real	0m3.094s
user	0m2.713s
sys	0m0.346s
```

This yielded to a modest improvement on my computer (time to run the test suite - cache deleted between runs):
- With the improvement: 19.20s
- Baseline: 19.88s

/cc @miketheman

2024-12-05 16:57 UTC, DarkaMaul commented
However, I believe the image in CI is built there :

https://github.com/pypi/warehouse/blob/c9231a69413f218adcc8c2236b78059f524eadb6/.github/workflows/ci.yml#L30-L38

But I don't know if it is safe to remove dependencies from there too or if this image is also used in other places.

2024-12-05 17:05 UTC, ewdurbin commented
Can the ddtrace plugin not be disabled in pytest?

2024-12-06 16:51 UTC, DarkaMaul commented
> Can the ddtrace plugin not be disabled in pytest?
It can but I _think_ it will still be loaded.

Let me check this and how it impacts the performance in the CI.

2024-12-09 09:20 UTC, DarkaMaul commented
There are two sets of complementary changes. The table below summarizes them, with the first line `build` representing the image [build](https://github.com/pypi/warehouse/blob/main/.github/workflows/ci.yml#L16) and [test](https://github.com/pypi/warehouse/blob/main/.github/workflows/ci.yml#L39) the testing job.

| | Baseline | Plugin disabled | Plugin not-installed |
|-|------|-----|----|
| `build` | / | 3m52s | 3m30s |
| `test` | 1m32s | 1m24s | 1m26s|

- The `build` changes (when the CI image is constructed) are not releveant because the image is cached by `depot` and then layers are re-used. We only benefit from not installing a package (and its dependencies) that is not used in the image.
- Disabling the plugin (either because it is not installed or because it is explicitly disabled) yields some nice improvements (about 8%)

Given the previous results - I think only disabling `trace` plugins in the tests is enough.

2024-12-09 13:23 UTC, miketheman requested changes
I'm fine with disabling the plugin for now - as we don't yet [integrate deeply with Datadog via ddtrace to advertise test timings](https://docs.datadoghq.com/tests/setup/python/?tab=ciproviderwithautoinstrumentationsupport) yet, but may wish to in the future.

Let's keep the installation around, since that simplifies the overall stack and removing it doesn't have a material impact on overall CI timings.

Testing only the `-p` additions to `pyproject.toml` drops about 50% test time on my machine as well, confirming the other timings you've shared.

2024-12-09 13:23 UTC, miketheman commented on Dockerfile
> +    								$(if [ "$TESTS" = "no" ]; then echo '-r /tmp/requirements/deploy.txt'; fi) \
nitpick: mixing spaces with tabs on this line. Don't fix if removing ;)

2024-12-09 13:23 UTC, miketheman commented on pyproject.toml
> +  "-p no:ddtrace.pytest_benchmark",
> Given the previous results - I think only disabling trace plugins in the tests is enough.

Then should this be the only change necessary, and restore the other changes proposed?

2024-12-09 17:13 UTC, merged